name: cinnamon_flutter_template_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ------------------------------------
  # Dependencies used throughout the app
  # When adding a dependency, don't forget to add a version number
  # Also, sort the dependencies alphabetically
  # ------------------------------------

  alice: ^0.2.5 # HTTP Inspector tool which helps debugging HTTP requests
  audioplayers: ^0.20.1 # Used to play audio files
  better_player: ^0.0.77 # Used to play video files
  cached_network_image: ^3.1.0 # Load and cache network images
  cell_calendar: ^0.6.0 # Used to show calendar on screen
  cloud_firestore: ^3.1.6 # Cloud-hosted, noSQL database
  connectivity_plus: ^2.0.2 # Used to check if device is connected to the network
  cupertino_icons: ^1.0.3 # Apple styled icons
  device_info_plus: ^3.1.0 # Get current device information
  dio: ^4.0.1 # Used as a HTTP client
  dots_indicator: ^2.0.0 #Shows dots on PageView
  firebase_auth: ^3.3.5 # Android and iOS authentication using passwords, etc.
  firebase_core: ^1.11.0 # Connects to Firebase services
  firebase_messaging: ^11.4.0 # Used for push notifications
  firebase_storage: ^10.2.5 # Used to connect to Firebase Storage
  flutter_screenutil: ^5.0.0+2 # Used for adapting screen and font size
  flutter_spinkit: ^5.1.0 # Collection of loading indicators
  flutter_svg: ^0.23.0+1 # SVG rendering library
  freezed_annotation: ^2.1.0 # Annotations for 'freezed'
  get: ^4.5.1 # State management, dependency injection, etc.
  get_storage: ^2.0.3 # Fast, light and synchronous key-value storage
  google_fonts: ^2.1.0 # Include fonts from fonts.google.com
  image_picker: ^0.8.4+4 # Choose image from gallery
  json_annotation: ^4.3.0 # Defines the annotations used by json_serializable
  json_serializable: ^6.0.1 # Automatically generate code for converting to and from JSON
  location: ^4.3.0 # Used for getting the device location
  logger: ^1.1.0 # Small, easy to use and extensible logger which prints beautiful logs
  open_file: ^3.2.1 # Used to open PDF files
  path_provider: ^2.0.10 # Used to get path of local folders
  permission_handler: ^8.2.5 # Used for easy permission handling
  photo_view: ^0.13.0 # Simple zoomable image/content widget
  pin_code_fields: ^7.3.0 # Used for pin code verification
  sensors_plus: ^1.2.1 # Used to access the accelerometer, gyroscope, and magnetometer sensors
  splashscreen: ^1.3.5 # Used to load initial screen that gets displayed right when the user launches the app, before the main page loads
  syncfusion_flutter_pdfviewer: ^20.1.50-beta # Used to view PDF documents
  url_launcher: ^6.0.12 # Used to launch URLs in native browser
  flutter_local_notifications: ^9.6.1
  http: ^0.13.4
  equatable: ^2.0.3
  freezed: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ------------------------------------
  # Dev dependencies used throughout the app
  # ------------------------------------

  build_runner: ^2.1.4 # Build system for Dart code generation
  flutter_launcher_icons: ^0.9.2 # Used to generate app icons
  flutter_native_splash: ^1.3.1 # Used to generate splash screen
  test: ^1.20.2
  mockito: ^5.2.0

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'flutter pub run flutter_launcher_icons:main'
flutter_icons:
  android: true
  ios: true
  image_path: 'assets/some_icon.png'
  adaptive_icon_background: '#FFFFFF'
  adaptive_icon_foreground: 'assets/some_icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'flutter pub run flutter_native_splash:create'
flutter_native_splash:
  android: true
  ios: true
  color: '#FFFFFF'
  image: 'assets/some_icon.png'

flutter:
  uses-material-design: true

  # Assets folder used throughout the app
  # Add specific folders you plan on using (e.g. 'assets/icons/')
  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: MontExtraLight
      fonts:
        - asset: assets/fonts/Mont-ExtraLight.otf
    - family: MontHeavy
      fonts:
        - asset: assets/fonts/Mont-Heavy.otf


